package com.sinfeeloo.inventory.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.id
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.goodsId
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.repoId
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private Integer repoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.totalCount
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private Integer totalcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.saleCount
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private Integer salecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.buyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private BigDecimal buyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.avgBuyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private BigDecimal avgbuyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.salePrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private BigDecimal saleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.totalBuyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private BigDecimal totalbuyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.totalSalePrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private BigDecimal totalsaleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.updatime
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private Date updatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_stock.state
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    private Integer state;


    private String goodsName;
    private String goodsCode;
    private String goodsType;
    private String goodsUnit;
    private String goodsStandard;
    private String storageName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.id
     *
     * @return the value of lz_stock.id
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.id
     *
     * @param id the value for lz_stock.id
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.goodsId
     *
     * @return the value of lz_stock.goodsId
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.goodsId
     *
     * @param goodsid the value for lz_stock.goodsId
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.repoId
     *
     * @return the value of lz_stock.repoId
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public Integer getRepoid() {
        return repoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.repoId
     *
     * @param repoid the value for lz_stock.repoId
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setRepoid(Integer repoid) {
        this.repoid = repoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.totalCount
     *
     * @return the value of lz_stock.totalCount
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.totalCount
     *
     * @param totalcount the value for lz_stock.totalCount
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.saleCount
     *
     * @return the value of lz_stock.saleCount
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public Integer getSalecount() {
        return salecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.saleCount
     *
     * @param salecount the value for lz_stock.saleCount
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setSalecount(Integer salecount) {
        this.salecount = salecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.buyPrice
     *
     * @return the value of lz_stock.buyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public BigDecimal getBuyprice() {
        return buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.buyPrice
     *
     * @param buyprice the value for lz_stock.buyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setBuyprice(BigDecimal buyprice) {
        this.buyprice = buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.avgBuyPrice
     *
     * @return the value of lz_stock.avgBuyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public BigDecimal getAvgbuyprice() {
        return avgbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.avgBuyPrice
     *
     * @param avgbuyprice the value for lz_stock.avgBuyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setAvgbuyprice(BigDecimal avgbuyprice) {
        this.avgbuyprice = avgbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.salePrice
     *
     * @return the value of lz_stock.salePrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public BigDecimal getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.salePrice
     *
     * @param saleprice the value for lz_stock.salePrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setSaleprice(BigDecimal saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.totalBuyPrice
     *
     * @return the value of lz_stock.totalBuyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public BigDecimal getTotalbuyprice() {
        return totalbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.totalBuyPrice
     *
     * @param totalbuyprice the value for lz_stock.totalBuyPrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setTotalbuyprice(BigDecimal totalbuyprice) {
        this.totalbuyprice = totalbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.totalSalePrice
     *
     * @return the value of lz_stock.totalSalePrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public BigDecimal getTotalsaleprice() {
        return totalsaleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.totalSalePrice
     *
     * @param totalsaleprice the value for lz_stock.totalSalePrice
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setTotalsaleprice(BigDecimal totalsaleprice) {
        this.totalsaleprice = totalsaleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.updatime
     *
     * @return the value of lz_stock.updatime
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public Date getUpdatime() {
        return updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.updatime
     *
     * @param updatime the value for lz_stock.updatime
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setUpdatime(Date updatime) {
        this.updatime = updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_stock.state
     *
     * @return the value of lz_stock.state
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_stock.state
     *
     * @param state the value for lz_stock.state
     *
     * @mbggenerated Thu May 03 10:43:21 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }


    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public String getGoodsCode() {
        return goodsCode;
    }

    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode;
    }

    public String getGoodsType() {
        return goodsType;
    }

    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType;
    }

    public String getGoodsUnit() {
        return goodsUnit;
    }

    public void setGoodsUnit(String goodsUnit) {
        this.goodsUnit = goodsUnit;
    }

    public String getGoodsStandard() {
        return goodsStandard;
    }

    public void setGoodsStandard(String goodsStandard) {
        this.goodsStandard = goodsStandard;
    }

    public String getStorageName() {
        return storageName;
    }

    public void setStorageName(String storageName) {
        this.storageName = storageName;
    }
}