package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Role;
import java.util.List;
import java.util.Map;

public interface RoleMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_role
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_role
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    List<Role> selectAll();




    /**
     * 添加
     * @param record
     * @return
     */
    int insert(Role record);

    /**
     * 通过名称查询该用户是否存在
     * @param name
     * @return
     */
    Role selectByName(String name);

    long selectRoleCount(Map<String, Object> searchMap);

    List<Role> selectRoleListByPage(Map<String, Object> searchMap);

    /**
     * 修改
     * @param record
     * @return
     */
    int updateByPrimaryKey(Role record);

    /**
     * 删除
     * @param id
     * @return
     */
    int deleteByPrimaryKey(Integer id);

}