package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Role;
import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_role
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_role
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_role
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_role
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_role
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int updateByPrimaryKey(Role record);
}