package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int updateByPrimaryKey(User record);

    User selectByAccount(String account);
}