package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.User;
import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sys_user
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int updateByPrimaryKey(User record);





    //==========================自定义开始======================================
    /**
     * 通过账号查询账户
     * @param account
     * @return
     */
    User selectByAccount(String account);

    /**
     * 添加用户
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    int insert(User record);

    /**
     * 分页总数量
     * @param searchMap
     * @return
     */
    long selectUserCount(Map<String, Object> searchMap);

    /**
     * 分页列表
     * @param searchMap
     * @return
     */
    List<User> selectUserListByPage(Map<String,Object> searchMap);

    //==========================自定义结束======================================
}