package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Employee;
import java.util.List;
import java.util.Map;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_employee
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_employee
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_employee
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    List<Employee> selectAll();

    /**
     * 修改
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int updateByPrimaryKey(Employee record);


    /**
     * 添加
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int insert(Employee record);

    long selectEmployeeListCount(Map<String, Object> searchMap);

    List<Employee> selectEmployeeListByPage(Map<String, Object> searchMap);
}