package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Goods;
import java.util.List;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_goods
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_goods
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_goods
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_goods
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    List<Goods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_goods
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int updateByPrimaryKey(Goods record);
}