package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Goods;

import java.util.List;
import java.util.Map;

public interface GoodsMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_goods
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    List<Goods> selectAll();


    /**
     * 添加
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int insert(Goods record);

    /**
     * 分页查询数量
     *
     * @param searchMap
     * @return
     */
    long selectGoodsListCount(Map<String, Object> searchMap);

    /**
     * 分页查询列表
     *
     * @param searchMap
     * @return
     */
    List<Goods> selectGoodsListByPage(Map<String, Object> searchMap);


    /**
     * 修改
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int updateByPrimaryKey(Goods goods);


    /**
     * 删除
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int deleteByPrimaryKey(Goods goods);


    /**
     * 查询
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    Goods selectByPrimaryKey(Integer id);


}