package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Param;
import java.util.List;
import java.util.Map;

public interface ParamMapper {
    /**
     * 删除
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     * @param id
     */
    int deleteByPrimaryKey(Param id);

    /**
     * 添加
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    int insert(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_param
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    Param selectByPrimaryKey(Integer id);


    /**
     * 修改
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    int updateByPrimaryKey(Param record);

    long selectParamListCount(Map<String, Object> searchMap);

    List<Param> selectParamListByPage(Map<String, Object> searchMap);
}