package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Param;
import java.util.List;

public interface ParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_param
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_param
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int insert(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_param
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    Param selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_param
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    List<Param> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_param
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int updateByPrimaryKey(Param record);
}