package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Storage;

import java.util.List;
import java.util.Map;

public interface StorageMapper {

    /**
     * 添加
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int insert(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_base_repo
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    Storage selectByPrimaryKey(Integer id);


    /**
     * 修改
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int updateByPrimaryKey(Storage record);

    long selectStorageCount(Map<String, Object> searchMap);

    List<Storage> selectStorageListByPage(Map<String, Object> searchMap);


    /**
     * 删除
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    int deleteByPrimaryKey(Storage storage);

}