package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_menu.id
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_menu.name
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_menu.upId
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private Integer upid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_menu.path
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_menu.isLeaf
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private Integer isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_menu.state
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_menu.updater
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_menu.updatime
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private Date updatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_menu.id
     *
     * @return the value of lz_sys_menu.id
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_menu.id
     *
     * @param id the value for lz_sys_menu.id
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_menu.name
     *
     * @return the value of lz_sys_menu.name
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_menu.name
     *
     * @param name the value for lz_sys_menu.name
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_menu.upId
     *
     * @return the value of lz_sys_menu.upId
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public Integer getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_menu.upId
     *
     * @param upid the value for lz_sys_menu.upId
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setUpid(Integer upid) {
        this.upid = upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_menu.path
     *
     * @return the value of lz_sys_menu.path
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_menu.path
     *
     * @param path the value for lz_sys_menu.path
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_menu.isLeaf
     *
     * @return the value of lz_sys_menu.isLeaf
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public Integer getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_menu.isLeaf
     *
     * @param isleaf the value for lz_sys_menu.isLeaf
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setIsleaf(Integer isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_menu.state
     *
     * @return the value of lz_sys_menu.state
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_menu.state
     *
     * @param state the value for lz_sys_menu.state
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_menu.updater
     *
     * @return the value of lz_sys_menu.updater
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_menu.updater
     *
     * @param updater the value for lz_sys_menu.updater
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_menu.updatime
     *
     * @return the value of lz_sys_menu.updatime
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public Date getUpdatime() {
        return updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_menu.updatime
     *
     * @param updatime the value for lz_sys_menu.updatime
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setUpdatime(Date updatime) {
        this.updatime = updatime;
    }
}