package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.id
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.name
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.code
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.descs
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.menuIds
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String menuids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.menuNames
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String menunames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.state
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.updater
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sys_role.updatime
     *
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    private Date updatime;

    private String updatimeStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.id
     *
     * @return the value of lz_sys_role.id
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.id
     *
     * @param id the value for lz_sys_role.id
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.name
     *
     * @return the value of lz_sys_role.name
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.name
     *
     * @param name the value for lz_sys_role.name
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.code
     *
     * @return the value of lz_sys_role.code
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.code
     *
     * @param code the value for lz_sys_role.code
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.descs
     *
     * @return the value of lz_sys_role.descs
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.descs
     *
     * @param descs the value for lz_sys_role.descs
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.menuIds
     *
     * @return the value of lz_sys_role.menuIds
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getMenuids() {
        return menuids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.menuIds
     *
     * @param menuids the value for lz_sys_role.menuIds
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setMenuids(String menuids) {
        this.menuids = menuids == null ? null : menuids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.menuNames
     *
     * @return the value of lz_sys_role.menuNames
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getMenunames() {
        return menunames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.menuNames
     *
     * @param menunames the value for lz_sys_role.menuNames
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setMenunames(String menunames) {
        this.menunames = menunames == null ? null : menunames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.state
     *
     * @return the value of lz_sys_role.state
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.state
     *
     * @param state the value for lz_sys_role.state
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.updater
     *
     * @return the value of lz_sys_role.updater
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.updater
     *
     * @param updater the value for lz_sys_role.updater
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sys_role.updatime
     *
     * @return the value of lz_sys_role.updatime
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public Date getUpdatime() {
        return updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sys_role.updatime
     *
     * @param updatime the value for lz_sys_role.updatime
     * @mbggenerated Wed Apr 25 17:12:01 CST 2018
     */
    public void setUpdatime(Date updatime) {
        this.updatime = updatime;
    }

    public String getUpdatimeStr() {
        return updatimeStr;
    }

    public void setUpdatimeStr(String updatimeStr) {
        this.updatimeStr = updatimeStr;
    }
}