package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Customer;
import java.util.List;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_customer
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_customer
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_customer
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    Customer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_customer
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    List<Customer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_customer
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    int updateByPrimaryKey(Customer record);
}