package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.SalesOrder;
import java.util.List;
import java.util.Map;

public interface SalesOrderMapper {
    /**
     * 添加
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    int insert(SalesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    SalesOrder selectByPrimaryKey(Integer id);


    /**
     * 修改
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    int updateByPrimaryKey(SalesOrder record);

    //分页列表
    List<SalesOrder> selectOrderListByPage(Map<String, Object> searchMap);
    //分页数量
    long selectOrderListCount(Map<String, Object> searchMap);


    /**
     * 删除
     * @param purchaseOrder
     * @return
     */
    int deleteByPrimaryKey(SalesOrder purchaseOrder);

    /**
     * 审核
     * @param order
     * @return
     */
    int updateCheckState(SalesOrder order);
}