package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.SalesOrder;
import java.util.List;

public interface SalesOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_order
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_order
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    int insert(SalesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_order
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    SalesOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_order
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    List<SalesOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_sale_order
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    int updateByPrimaryKey(SalesOrder record);
}