package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Order;
import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:29:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:29:31 CST 2018
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:29:31 CST 2018
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:29:31 CST 2018
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:29:31 CST 2018
     */
    int updateByPrimaryKey(Order record);
}