package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.PurchaseOrder;
import java.util.List;

public interface PurchaseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    int insert(PurchaseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    PurchaseOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    List<PurchaseOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_order
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    int updateByPrimaryKey(PurchaseOrder record);
}