package com.sinfeeloo.inventory.mapper;

import com.sinfeeloo.inventory.entity.Supplier;
import java.util.List;
import java.util.Map;

public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_supplier
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     * @param id
     */
    int deleteByPrimaryKey(Supplier id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_supplier
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_supplier
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    Supplier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_supplier
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    List<Supplier> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lz_purchase_supplier
     *
     * @mbggenerated Thu May 03 10:36:58 CST 2018
     */
    int updateByPrimaryKey(Supplier record);

    List<Supplier> selectSupperListByPage(Map<String, Object> searchMap);

    long selectSupperListCount(Map<String, Object> searchMap);
}