package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.id
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.name
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.linkman
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.mobile
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.address
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.descs
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.state
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.updater
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_sale_customer.updatime
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    private Date updatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.id
     *
     * @return the value of lz_sale_customer.id
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.id
     *
     * @param id the value for lz_sale_customer.id
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.name
     *
     * @return the value of lz_sale_customer.name
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.name
     *
     * @param name the value for lz_sale_customer.name
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.linkman
     *
     * @return the value of lz_sale_customer.linkman
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.linkman
     *
     * @param linkman the value for lz_sale_customer.linkman
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.mobile
     *
     * @return the value of lz_sale_customer.mobile
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.mobile
     *
     * @param mobile the value for lz_sale_customer.mobile
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.address
     *
     * @return the value of lz_sale_customer.address
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.address
     *
     * @param address the value for lz_sale_customer.address
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.descs
     *
     * @return the value of lz_sale_customer.descs
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.descs
     *
     * @param descs the value for lz_sale_customer.descs
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.state
     *
     * @return the value of lz_sale_customer.state
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.state
     *
     * @param state the value for lz_sale_customer.state
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.updater
     *
     * @return the value of lz_sale_customer.updater
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.updater
     *
     * @param updater the value for lz_sale_customer.updater
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_sale_customer.updatime
     *
     * @return the value of lz_sale_customer.updatime
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public Date getUpdatime() {
        return updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_sale_customer.updatime
     *
     * @param updatime the value for lz_sale_customer.updatime
     *
     * @mbggenerated Thu May 03 10:36:23 CST 2018
     */
    public void setUpdatime(Date updatime) {
        this.updatime = updatime;
    }
}