package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.code
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.idCard
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.mobile
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.sex
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer sex;
    private String sexStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.birthday
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Date birthday;
    private String birthdayStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.address
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.email
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.type
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer type;
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.updater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.updatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Date updatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_employee.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.id
     *
     * @return the value of lz_base_employee.id
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.id
     *
     * @param id the value for lz_base_employee.id
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.name
     *
     * @return the value of lz_base_employee.name
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.name
     *
     * @param name the value for lz_base_employee.name
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.code
     *
     * @return the value of lz_base_employee.code
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.code
     *
     * @param code the value for lz_base_employee.code
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.idCard
     *
     * @return the value of lz_base_employee.idCard
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.idCard
     *
     * @param idcard the value for lz_base_employee.idCard
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.mobile
     *
     * @return the value of lz_base_employee.mobile
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.mobile
     *
     * @param mobile the value for lz_base_employee.mobile
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.sex
     *
     * @return the value of lz_base_employee.sex
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.sex
     *
     * @param sex the value for lz_base_employee.sex
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setSex(Integer sex) {
        this.sexStr = String.valueOf(sex);
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.birthday
     *
     * @return the value of lz_base_employee.birthday
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.birthday
     *
     * @param birthday the value for lz_base_employee.birthday
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.address
     *
     * @return the value of lz_base_employee.address
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.address
     *
     * @param address the value for lz_base_employee.address
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.email
     *
     * @return the value of lz_base_employee.email
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.email
     *
     * @param email the value for lz_base_employee.email
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.updater
     *
     * @return the value of lz_base_employee.updater
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.updater
     *
     * @param updater the value for lz_base_employee.updater
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.updatime
     *
     * @return the value of lz_base_employee.updatime
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Date getUpdatime() {
        return updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.updatime
     *
     * @param updatime the value for lz_base_employee.updatime
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setUpdatime(Date updatime) {
        this.updatime = updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_employee.state
     *
     * @return the value of lz_base_employee.state
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_employee.state
     *
     * @param state the value for lz_base_employee.state
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public String getBirthdayStr() {
        return birthdayStr;
    }

    public void setBirthdayStr(String birthdayStr) {
        this.birthdayStr = birthdayStr;
    }
}