package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.code
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.type
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.brand
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.unit
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.color
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.standard
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.material
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.buyPrice
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String buyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.salePrice
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String saleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.updater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.updatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Date updatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_goods.picture
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.id
     *
     * @return the value of lz_base_goods.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.id
     *
     * @param id the value for lz_base_goods.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.name
     *
     * @return the value of lz_base_goods.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.name
     *
     * @param name the value for lz_base_goods.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.code
     *
     * @return the value of lz_base_goods.code
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.code
     *
     * @param code the value for lz_base_goods.code
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.type
     *
     * @return the value of lz_base_goods.type
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.type
     *
     * @param type the value for lz_base_goods.type
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.brand
     *
     * @return the value of lz_base_goods.brand
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.brand
     *
     * @param brand the value for lz_base_goods.brand
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.unit
     *
     * @return the value of lz_base_goods.unit
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.unit
     *
     * @param unit the value for lz_base_goods.unit
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.color
     *
     * @return the value of lz_base_goods.color
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.color
     *
     * @param color the value for lz_base_goods.color
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.standard
     *
     * @return the value of lz_base_goods.standard
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.standard
     *
     * @param standard the value for lz_base_goods.standard
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.material
     *
     * @return the value of lz_base_goods.material
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.material
     *
     * @param material the value for lz_base_goods.material
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.buyPrice
     *
     * @return the value of lz_base_goods.buyPrice
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getBuyprice() {
        return buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.buyPrice
     *
     * @param buyprice the value for lz_base_goods.buyPrice
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setBuyprice(String buyprice) {
        this.buyprice = buyprice == null ? null : buyprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.salePrice
     *
     * @return the value of lz_base_goods.salePrice
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.salePrice
     *
     * @param saleprice the value for lz_base_goods.salePrice
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setSaleprice(String saleprice) {
        this.saleprice = saleprice == null ? null : saleprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.descs
     *
     * @return the value of lz_base_goods.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.descs
     *
     * @param descs the value for lz_base_goods.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.updater
     *
     * @return the value of lz_base_goods.updater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.updater
     *
     * @param updater the value for lz_base_goods.updater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.updatime
     *
     * @return the value of lz_base_goods.updatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Date getUpdatime() {
        return updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.updatime
     *
     * @param updatime the value for lz_base_goods.updatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setUpdatime(Date updatime) {
        this.updatime = updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.state
     *
     * @return the value of lz_base_goods.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.state
     *
     * @param state the value for lz_base_goods.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_goods.picture
     *
     * @return the value of lz_base_goods.picture
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_goods.picture
     *
     * @param picture the value for lz_base_goods.picture
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }
}