package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_image.id
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_image.file_name
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_image.file_path
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_image.updatetime
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_image.id
     *
     * @return the value of lz_base_image.id
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_image.id
     *
     * @param id the value for lz_base_image.id
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_image.file_name
     *
     * @return the value of lz_base_image.file_name
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_image.file_name
     *
     * @param fileName the value for lz_base_image.file_name
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_image.file_path
     *
     * @return the value of lz_base_image.file_path
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_image.file_path
     *
     * @param filePath the value for lz_base_image.file_path
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_image.updatetime
     *
     * @return the value of lz_base_image.updatetime
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_image.updatetime
     *
     * @param updatetime the value for lz_base_image.updatetime
     *
     * @mbggenerated Wed May 02 13:14:18 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}