package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Param {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.type
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.creater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.creatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Date creatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.id
     *
     * @return the value of lz_base_param.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.id
     *
     * @param id the value for lz_base_param.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.name
     *
     * @return the value of lz_base_param.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.name
     *
     * @param name the value for lz_base_param.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.descs
     *
     * @return the value of lz_base_param.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.descs
     *
     * @param descs the value for lz_base_param.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.state
     *
     * @return the value of lz_base_param.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.state
     *
     * @param state the value for lz_base_param.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.type
     *
     * @return the value of lz_base_param.type
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.type
     *
     * @param type the value for lz_base_param.type
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.creater
     *
     * @return the value of lz_base_param.creater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.creater
     *
     * @param creater the value for lz_base_param.creater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.creatime
     *
     * @return the value of lz_base_param.creatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.creatime
     *
     * @param creatime the value for lz_base_param.creatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }
}