package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Param {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.id
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.name
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.descs
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.state
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private Integer state;
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.type
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.creater
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.creatime
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private Date creatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.updatetime
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_param.updater
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    private String updater;
    private String creatimeStr;
    private String updatetimeStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.id
     *
     * @return the value of lz_base_param.id
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.id
     *
     * @param id the value for lz_base_param.id
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.name
     *
     * @return the value of lz_base_param.name
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.name
     *
     * @param name the value for lz_base_param.name
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.descs
     *
     * @return the value of lz_base_param.descs
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.descs
     *
     * @param descs the value for lz_base_param.descs
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.state
     *
     * @return the value of lz_base_param.state
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.state
     *
     * @param state the value for lz_base_param.state
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getTypeid() {
        return typeid;
    }

    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    public String getTypename() {
        return typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.creater
     *
     * @return the value of lz_base_param.creater
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.creater
     *
     * @param creater the value for lz_base_param.creater
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.creatime
     *
     * @return the value of lz_base_param.creatime
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.creatime
     *
     * @param creatime the value for lz_base_param.creatime
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.updatetime
     *
     * @return the value of lz_base_param.updatetime
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.updatetime
     *
     * @param updatetime the value for lz_base_param.updatetime
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_param.updater
     *
     * @return the value of lz_base_param.updater
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_param.updater
     *
     * @param updater the value for lz_base_param.updater
     *
     * @mbggenerated Thu May 03 09:56:04 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    public String getCreatimeStr() {
        return creatimeStr;
    }

    public void setCreatimeStr(String creatimeStr) {
        this.creatimeStr = creatimeStr;
    }

    public String getUpdatetimeStr() {
        return updatetimeStr;
    }

    public void setUpdatetimeStr(String updatetimeStr) {
        this.updatetimeStr = updatetimeStr;
    }
}