package com.sinfeeloo.inventory.entity;

import java.util.Date;

public class Storage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.code
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.address
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.adminId
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.updater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.updatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Date updatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lz_base_repo.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.id
     *
     * @return the value of lz_base_repo.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.id
     *
     * @param id the value for lz_base_repo.id
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.name
     *
     * @return the value of lz_base_repo.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.name
     *
     * @param name the value for lz_base_repo.name
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.code
     *
     * @return the value of lz_base_repo.code
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.code
     *
     * @param code the value for lz_base_repo.code
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.address
     *
     * @return the value of lz_base_repo.address
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.address
     *
     * @param address the value for lz_base_repo.address
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.descs
     *
     * @return the value of lz_base_repo.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.descs
     *
     * @param descs the value for lz_base_repo.descs
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.adminId
     *
     * @return the value of lz_base_repo.adminId
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.adminId
     *
     * @param adminid the value for lz_base_repo.adminId
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.updater
     *
     * @return the value of lz_base_repo.updater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.updater
     *
     * @param updater the value for lz_base_repo.updater
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.updatime
     *
     * @return the value of lz_base_repo.updatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Date getUpdatime() {
        return updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.updatime
     *
     * @param updatime the value for lz_base_repo.updatime
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setUpdatime(Date updatime) {
        this.updatime = updatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lz_base_repo.state
     *
     * @return the value of lz_base_repo.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lz_base_repo.state
     *
     * @param state the value for lz_base_repo.state
     *
     * @mbggenerated Tue Apr 24 17:00:10 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}